- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/toilets_controller.rb
- app/models/toilet.rb
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/pages/home.html.erb
- app/views/toilets/index.html.erb
- app/views/toilets/new.html.erb
- config/routes.rb
- db/migrate/20191118142442_create_toilets.rb
- db/migrate/20191118144406_change_column_name_to_toilets.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/toilets_controller_test.rb
- test/models/toilet_test.rb
@HadrienDT Please review dude !
We've added the user + toilet model. 
Action new, index and create have been added for toilets
Action sign up, sign in and sign out have been added for users
> added toilet model and controller with index, new and create

- app/assets/stylesheets/components/_cards.scss
- app/views/toilets/index.html.erb
@remichat please review :)
what do you think ?
> updated index waiting for the seed

- Gemfile
- Gemfile.lock
- app/models/toilet.rb
- app/models/user.rb
- db/seeds.rb
I changed the users password for an easier one.
> Seeds creation

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_radio.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/toilets_controller.rb
- app/models/toilet.rb
- app/views/layouts/application.html.erb
- app/views/toilets/edit.html.erb
- app/views/toilets/edit_2.html.erb
- app/views/toilets/index.html.erb
- app/views/toilets/new.html.erb
- config/routes.rb
@ronanquerrec 
I added a 2 steps toilet creation plus improved a few things (doc title, scss best practices)
> Create add toilet feature

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/toilets/show.html.erb
- package.json
- yarn.lock
@remichat 
to be checked:
- booking form feature (with time)
not to be checked:
- style
- link with booking model
> add booking form to show

- db/migrate/20191119145853_create_active_storage_tables.active_storage.rb
- db/schema.rb
> installed active storage

- app/controllers/toilets_controller.rb
- config/routes.rb
> routes updated

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_bookingf.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/toilets/show.html.erb
@remichat, WIP sur la show:
- booking form avec style
- datas sur col gauche
> show style WIP

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/toilets_controller.rb
- app/views/toilets/edit_2.html.erb
- app/views/toilets/edit_3.html.erb
- app/views/toilets/new.html.erb
@ronanquerrec 
Improved the toilet creation to 3 steps and added fonts
> better toilet creation

- app/views/layouts/application.html.erb
@remichat 
Correctif style booking form dans show toilet.html
> fixed booking form style

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_show.scss
- app/models/toilet.rb
- app/views/toilets/show.html.erb
@ronanquerrec 
improved show toilet
> Improve toilet show style

- app/assets/stylesheets/components/_avatar.scss
- app/views/shared/_navbar.html.erb
@remichat 
navbar: active off + margin left sur avatar
> nav bar margin and active

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
There was a missing import in the index.scss
> Fixed the Bookings index style issue

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_layout.scss
- app/views/toilets/index.html.erb
@JulesBayon @remichat @ronanquerrec 
please review my code :)
I've added gender icons on cards, line-height in banner, and blue button
> gender icons added + modified button color

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_bookingf.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_show.scss
- app/models/toilet.rb
- app/views/layouts/application.html.erb
- app/views/toilets/show.html.erb
> clean show toilet with stars and tag on picture and changed layout

- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- app/views/toilets/index.html.erb
- package.json
- yarn.lock
@remichat 
I've added some scroll animations, what do you think ?
> animation on scroll added

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_layout.scss
- app/views/layouts/application.html.erb
@JulesBayon fixed footer position
> fixed footer position

- app/assets/stylesheets/components/_form_login.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/toilets_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
> login working

- db/seeds.rb
Removed fake toilet cards, added one alamano.
> Enriched the seed

- app/javascript/plugins/flatpickr.js
- app/views/toilets/show.html.erb
@JulesBayon 
booking form : style du choix de l'heure
> Datepicker imprvmnt

- app/controllers/bookings_controller.rb
- app/controllers/owner/bookings_controller.rb
- app/models/user.rb
- app/views/owner/bookings/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20191119144853_create_bookings.rb
> added booking validation feature

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_bookingf.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_index_toilets.scss
- app/views/toilets/index.html.erb
- app/views/toilets/show.html.erb
- config/initializers/geocoder.rb
@remichat 
ajout tickers + stars sur index + clean sur orga CSS
> Add ticker index

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_search-bar.scss
- app/assets/stylesheets/pages/_layout.scss
- app/controllers/pages_controller.rb
- app/controllers/toilets_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/toilet.rb
- app/views/pages/home.html.erb
- app/views/shared/_info_window.html.erb
- app/views/shared/_navbar.html.erb
- app/views/toilets/index.html.erb
- config/initializers/geocoder.rb
- config/routes.rb
- db/migrate/20191121094641_add_coordinates_to_toilets.rb
- db/schema.rb
- db/seeds.rb
- package.json
- test/controllers/pages_controller_test.rb
- yarn.lock
@remichat @ronanquerrec @JulesBayon 
new homepage with larger banner
search bar on banner redirecting to new page index
geocode is added
> Add geocoder

- app/assets/stylesheets/components/_card_product.scss
- app/views/bookings/index.html.erb
- app/views/owner/bookings/index.html.erb
Coulour code depending on booking status added in bookings index
> Bookings index improve 2.0.

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_search-bar.scss
- app/assets/stylesheets/pages/_layout.scss
- app/views/toilets/index.html.erb
@JulesBayon @ronanquerrec @remichat 
please review this awesome airbnb index
> addind airbnb style to index

- app/assets/stylesheets/components/_navbar.scss
@JulesBayon 
merge moi ça salope ❤️
> change font in navbar

- app/views/owner/bookings/index.html.erb
Owner index classification is now depending on the booking status
> En cours / Bookings list in owner index

- app/assets/stylesheets/components/_navbar.scss
@JulesBayon 
Hover navbar ma gueule
thx
> hover-navbar2
